version: '3.8'

services:
  whatsapp-service:
    image: devpedrohfreitas/whatsappapi
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - whatsapp-data:/app/.wwebjs_auth
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    restart: unless-stopped

volumes:
  whatsapp-data:
    name: whatsapp-data