name: Build e Export Docker

on:
  push:
    branches:
      - main  # Executa quando houver push na branch principal
  workflow_dispatch:  # Permite execução manual

jobs:
  build-and-export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Build da imagem Docker
        run: |
          docker build -t whatsappapi-node:latest .

      - name: Exportar a imagem Docker como arquivo .tar
        run: |
          docker save -o whatsappapi-node.tar whatsappapi-node:latest

      - name: Fazer upload do arquivo .tar como artefato
        uses: actions/upload-artifact@v4
        with:
          name: whatsappapi-node-image
          path: whatsappapi-node.tar
